services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    restart: always
    ports:
      - "9090:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      - HOST=0.0.0.0
      - OLLAMA_BASE_URL=http://192.168.0.48:11434
      - WEBUI_URL=http://192.168.0.48:9090
      - WEBUI_SECRET_KEY=${WEBUI_SECRET_KEY}
    volumes:
      - open-webui-data:/app/backend/data
      - /mnt/c/Repositories:/data/repositories

volumes:
  open-webui-data:
